# site
site_name: The Book of the Runtime
site_url: https://jurakovic.github.io/runtime/

# repo
repo_name: dotnet/runtime
repo_url: https://github.com/dotnet/runtime
edit_uri: edit/main/docs/design/coreclr/botr/

# docs
docs_dir: 'docs/design/coreclr/botr'

theme:
  name: material
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.view
    - navigation.footer
    - navigation.instant
    - navigation.indexes

plugins:
  - search
  - awesome-pages

extra:
  analytics:
    provider: google
    property: G-233EMZJM16
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jurakovic/runtime
    - icon: fontawesome/brands/github
      link: https://github.com/dotnet/runtime

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Introduction: README.md
  - Book of the Runtime FAQ: botr-faq.md
  - Introduction to the Common Language Runtime: intro-to-clr.md
  - Garbage Collection Design: garbage-collection.md
  - Threading: threading.md
  - RyuJIT Overview: ryujit-overview.md
  - Porting RyuJIT to other platforms: porting-ryujit.md
  - Type System: type-system.md
  - Type Loader: type-loader.md
  - Method Descriptor: method-descriptor.md
  - Virtual Stub Dispatch: virtual-stub-dispatch.md
  - Stack Walking: stackwalking.md
  - System.Private.CoreLib and calling into the runtime: corelib.md
  - Data Access Component (DAC) Notes: dac-notes.md
  - Profiling: profiling.md
  - Implementing Profilability: profilability.md
  - What Every Dev needs to Know About Exceptions in the Runtime: exceptions.md
  - ReadyToRun Overview: readytorun-overview.md
  - CLR ABI: clr-abi.md
  - Cross-platform Minidumps: xplat-minidump-generation.md
  - Mixed Mode Assemblies: mixed-mode.md
  - Guide For Porting: guide-for-porting.md
  - Vectors and Intrinsics: vectors-and-intrinsics.md
  #- ... # messes up all titles
  - ilc-architecture.md
  - managed-type-system.md
  - r2r-perfmap-format.md
  - readytorun-format.md
  - readytorun-platform-native-envelope.md
  - shared-generics.md
  - logging.md
